# testing read_vic_schools_fte function
# there is no URL, urls$read_vic_schools_fte is NULL

test_that("read_vic_schools_fte works", {

  fte <- read_vic_schools_fte()

  expect_s3_class(fte, 'data.frame')
  expect_equal(class(fte$school_no), 'numeric')
  expect_equal(class(fte$year), 'character')    # should that be 'Date'?

  expect_equal(colnames(fte), c("education_sector",
                                "entity_type",
                                "school_no",
                                "school_name",
                                "school_type",
                                "school_status",
                                "prep males total",
                                "prep females total",
                                "prep total",
                                "year 1 males total",
                                "year 1 females total",
                                "year 1 total",
                                "year 2 males total",
                                "year 2 females total",
                                "year 2 total",
                                "year 3 males total",
                                "year 3 females total",
                                "year 3 total",
                                "year 4 males total",
                                "year 4 females total",
                                "year 4 total",
                                "year 5 males total",
                                "year 5 females total",
                                "year 5 total",
                                "year 6 males total",
                                "year 6 females total",
                                "year 6 total",
                                "primary ungraded males total",
                                "primary ungraded females total",
                                "primary ungraded total",
                                "primary total",
                                "year 7 males total",
                                "year 7 females total",
                                "year 7 total",
                                "year 8 males total",
                                "year 8 females total",
                                "year 8 total",
                                "year 9 males total",
                                "year 9 females total",
                                "year 9 total",
                                "year 10 males total",
                                "year 10 females total",
                                "year 10 total",
                                "year 11 males total",
                                "year 11 females total",
                                "year 11 total",
                                "year 12 males",
                                "year 12 females",
                                "year 12 total",
                                "secondary ungraded males total",
                                "secondary ungraded females total",
                                "secondary ungraded total",
                                "secondary total",
                                "grand total",
                                "year",
                                "prep males",
                                "prep females",
                                "year 1 males",
                                "year 1 females",
                                "year 2 males",
                                "year 2 females",
                                "year 3 males",
                                "year 3 females",
                                "year 4 males",
                                "year 4 females",
                                "year 5 males",
                                "year 5 females",
                                "year 6 males",
                                "year 6 females",
                                "primary ungraded males",
                                "primary ungraded females",
                                "year 7 males",
                                "year 7 females",
                                "year 8 males",
                                "year 8 females",
                                "year 9 males",
                                "year 9 females",
                                "year 10 males",
                                "year 10 females",
                                "year 11 males",
                                "year 11 females",
                                "postprimary ungraded males",
                                "postprimary ungraded females",
                                "postprimary ungraded total",
                                "census_type"))

})
